stages:
    - deploy

Deploy to Heroku:
    stage: deploy
    image: ruby:latest
    only:
        - main
    script:
        - gem install dpl
        - cd Backend
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
